catagory_choices = [
        ('income', 'Income'),
        ('food', 'Food'),
        ('transport', 'Transport'),
        ('utilities', 'Utilities'),
        ('entertainment', 'Entertainment'),
        ('health', 'Health'),
        ('education', 'Education'),
        ('clothing', 'Clothing'),
        ('housing', 'Housing'),
        ('savings', 'Savings'),
        ('investment', 'Investment'),
        ('miscellaneous', 'Miscellaneous'),
        ('tax','Tax'),
    ]